### ISSUE TITLE
File loading failed!

### ISSUE THREAD

**Issue by perceptron8** [perceptron8/pinky.cr#12]
Similar to #5, but not the same. Work in progress.

**Comment by perceptron8** [comment]
"File loading failed! Please check your network connection, clean your browser cache or try again alter."

**Comment by Babaluuuuu** [comment]
I cannot get any collectibles anymore...

**Comment by Babaluuuuu** [comment]
...and file loading fails- collectibles invisible- What can I do now? I am desperate

**Comment by perceptron8** [comment]
Please, be patient. I'm searching for solution.
You may need to temporarily disable Pinky.
I'll let you know if something changes.

**Comment by Babaluuuuu** [comment]
great- ty so much- u know halloween event is coming up- wd be difficult without your precious app to find the collectibles....Best Regards and Good Luck

      Von: Michał Sobkiewicz <notifications@github.com>
 An: perceptron8/pinky.cr <pinky.cr@noreply.github.com> 
CC: Babaluuuuu <Beebeatrice@yahoo.de>; Comment <comment@noreply.github.com>
 Gesendet: 19:35 Donnerstag, 15.September 2016
 Betreff: Re: [perceptron8/pinky.cr] File loading failed! (#12)
   
Please, be patient. I'm searching for solution.
You may need to temporarily disable Pinky.
I'll let you know if something changes.—

**Comment by Timonx** [comment]
hi !

try to return at v22.0.0.209 of your flash player...

**Comment by perceptron8** [comment]
@Timonx Thanks!
I'll try to find some workaround.

**Comment by Babaluuuuu** [comment]
I am not very familiar with my new Windows 10- if I try to install flash player 22.0.0.209 (which version? 32 or 64 bit) it does not open and install, asking me with what I do want to open it???Thanks for your help

      Von: Timonx <notifications@github.com>
 An: perceptron8/pinky.cr <pinky.cr@noreply.github.com> 
CC: Babaluuuuu <Beebeatrice@yahoo.de>; Comment <comment@noreply.github.com>
 Gesendet: 11:33 Freitag, 16.September 2016
 Betreff: Re: [perceptron8/pinky.cr] File loading failed! (#12)
   
hi !try to return at v22.0.0.209 of your flash player...—

**Comment by perceptron8** [comment]
@Babaluuuuu See: https://helpx.adobe.com/flash-player/kb/flash-player-google-chrome.html. Most likely you will need a 64 bit version.

**Comment by Timonx** [comment]
thanks perceptron8 for your good job ;)

sorry for my bad english, I'm frensh :p

I think the problem comes from API (particulary chrome.webrequest) with Flash for Chrome : 
cf. old topic at : https://bugbase.adobe.com/index.cfm?event=bug&id=3711074

Perhaps is it the same bug ?

**Comment by perceptron8** [comment]
@Timonx I'm from Poland, so don't worry :) I know about 3711074, please see https://github.com/perceptron8/pinky.cr/issues/5#issuecomment-166103757.

I'm going to create some proxy and redirect request with 307. If it succeeds, then it's API. If not, it's incorrect redirect handling in general.

Thanks again :)

**Comment by perceptron8** [comment]
1. Using Jetty, I've created transparent proxy. I've added filter that redirects collectible requests (with 307, but I checked 302 and 301 also) to dummy.png. I've loaded TSO with Chrome, Firefox and IE12 (after making all of them use my proxy server). "File loading failed!", one after another. It is likely none of PPAPI (Chrome), NPAPI (Firefox), ActiveX (IE12) problem.

2. Using FlashDevelop, I've created a simple swf that makes single request to one of collectibles at static.ubi.com. Suprise! Everything works as expected. With Pinky enabled, collectible becomes pink rectangle. It's clearly neither chrome.webRequest API, nor Pinky. BTW it was Flash 23!

Because of 2), I suppose it's not redirect handling in general as I thought previously. 1) makes me think that it's something in TSO.

**Comment by perceptron8** [comment]
[Error #2048] sent to /log? Is it crossdomain issue?

**Comment by perceptron8** [comment]
I was able to reproduce "File loading failed!" on:
- Chrome 52.0.2743.116 (64-bit), Shockwave Flash 22.0 r0 (22.0.0.209),
- Chrome 53.0.2785.116 (64-bit), Shockwave Flash 23.0 r0 (23.0.0.162).
This, again, points to TSO change.

**Comment by perceptron8** [comment]
Another clue! Validity period of https://dummyimage.com certificate:
- Issued On:	Wednesday, September 14, 2016 at 1:40:00 PM,
- Expires On:	Tuesday, December 13, 2016 at 12:40:00 PM.

Did they switched from http to https?

**Comment by perceptron8** [comment]
I'm waiting for dummyimage.com administrator reaction...

**Comment by perceptron8** [comment]
This is workaround but it may stay forever. Instead of redirecting to dummyimage.com, I decided to use most uniformly pink image from static.cdn.ubi.com. It's not so bad.

Here it is: ed63ed0. Say goodbye to crossdomain issues!

**Comment by perceptron8** [comment]
You may now update Pinky to 0.1.15!

**Comment by shpreetz** [comment]
Thanks guys, the new version works perfect!
Getting ready for Halloween event ;)
