### ISSUE TITLE
File loading failed

### ISSUE THREAD

**Issue by qawpaw** [perceptron8/pinky.cr#13]
old problem is back again

**Comment by perceptron8** [comment]
Duplicate of #12.

**Comment by perceptron8** [comment]
1. What server do you use (http://www.tsotesting.com, http://www.thesettlersonline.com, etc.)?
2. Which Chrome version do you use (see chrome://version/)?
3. Which Flash version do you use (see chrome://plugins/)?
4. Which Pinky version do you use (see chrome://extensions/)

I'm unable to reproduce this issue on Pinky 0.1.15. I was able to get some "File loading failed!" on tsotesting.com, however it's surely unrelated to this extension.

**Comment by perceptron8** [comment]
Unconfirmed.
