### ISSUE TITLE
Scenario 

### ISSUE THREAD

**Issue by radeletp** [perceptron8/pinky.cr#2]
Would be good to add the collectibles needed in scenarios inside the list of collectibles. If needed, I can help to find the name of the png if you want, just let me know how they could be found?

**Comment by perceptron8** [comment]
Hi!

You can use [Chrome DevTools](https://developer.chrome.com/devtools) to inspect web requests and check if they relate to collectibles. Urls are always like http://static.cdn.ubi.com/0018/live/GFX_HASHED/building_lib/*.png.
That's what I used to do. Now I get file list from another source. Can't tell much about it, as I'm not sure if it's perfectly legal. Commit af85b8a41af2a176f84ff1c3dc95def638fa2099 should resolve this issue.

Pinky v0.1.7 is now available in [Chrome Web Store](https://chrome.google.com/webstore/detail/pinky/eijmklfnehnnkbfcoabieogaomookbna). Please, let me know if everything works as expected!

Feel free to comment / open another issue when something breaks. I don't play scenarios, so I may not be able to notice bugs. Nevertheless, I'll do my best to keep collectibles list up to date.

Thank you for feedback and willingness to help!

**Comment by perceptron8** [comment]
I just added 2 missing images. Pinky v0.1.8 will be available in about 60 minutes.

**Comment by radeletp** [comment]
Tested on some scenarios and it is working well, didn't find any item which is not pinked. Thanks a lot for the quick implementation,
